"""add template and post_times to user_channels

Revision ID: 4156c9564e69
Revises: 58cc7926f904
Create Date: 2025-07-31 19:37:46.478882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4156c9564e69'
down_revision: Union[str, None] = '58cc7926f904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('template', sa.String(), nullable=True))
    op.add_column('user_channels', sa.Column('post_times', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('user_channels', sa.Column('posts_per_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('registration_step', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_step')
    op.drop_column('user_channels', 'posts_per_day')
    op.drop_column('user_channels', 'post_times')
    op.drop_column('user_channels', 'template')
    # ### end Alembic commands ###
