"""upgrade

Revision ID: 58cc7926f904
Revises: 63fcef01bac4
Create Date: 2025-07-25 14:36:52.870240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58cc7926f904'
down_revision: Union[str, None] = '63fcef01bac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_channels', sa.Column('custom_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_channels', 'custom_prompt')
    # ### end Alembic commands ###
