"""Add template/post_times/posts_per_day

Revision ID: 8f74641daf2b
Revises: 4156c9564e69
Create Date: 2025-08-02 19:06:24.543651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f74641daf2b'
down_revision: Union[str, None] = '4156c9564e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
